// <auto-generated />
using System;
using DhanakTrinket.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DhanakTrinket.Infrastructure.Migrations
{
    [DbContext(typeof(DhanakTrinketDbContext))]
    [Migration("20260526144314_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("DhanakTrinket.Core.Entities.BulkSaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Quantity");

                    b.Property<int>("SaleId");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.ToTable("BulkSaleItems");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BillImagePath")
                        .HasMaxLength(500);

                    b.Property<int>("Category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<DateTime>("ExpenseDate");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<string>("VendorName")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsInStock");

                    b.Property<int>("LikesCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal?>("PariFestPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(5);

                    b.Property<int>("StockQuantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsInStock");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsPrimary");

                    b.Property<int>("ProductId");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuyerName")
                        .HasMaxLength(255);

                    b.Property<string>("BuyerPhone")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(255);

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<int?>("ProductId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("QuantitySold");

                    b.Property<string>("SaleChannel")
                        .HasMaxLength(100);

                    b.Property<DateTime>("SaleDate");

                    b.Property<int>("SaleType");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleDate");

                    b.HasIndex("SaleType");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.BulkSaleItem", b =>
                {
                    b.HasOne("DhanakTrinket.Core.Entities.Sale", "Sale")
                        .WithMany("BulkSaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("DhanakTrinket.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Sale", b =>
                {
                    b.HasOne("DhanakTrinket.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DhanakTrinket.Core.Entities.Sale", b =>
                {
                    b.Navigation("BulkSaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
